
services:
    labApp-db:
        image: mysql:8
        command:
            --collation-server=utf8mb4_0900_bin
            --transaction-isolation=READ-COMMITTED
        restart: always
        environment:
            MYSQL_DATABASE: labmanage
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: labuser
            MYSQL_PASSWORD: labpassword
            TZ: Asia/Tokyo
        ports:
            - 53307:3306
