# Generated by Django 6.0.6 on 2026-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "未登録"),
                            (1, "在室予定あり"),
                            (2, "在室予定なし"),
                        ],
                        default=0,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "member",
            },
        ),
    ]
